stages:
  - build
  - deploy

build:
  image: docker:19.03
  services:
    - docker:19.03-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  tags:
    - image-builder
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker pull $CI_REGISTRY_IMAGE/minio:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/minio:latest --tag $CI_REGISTRY_IMAGE/minio:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE/minio:latest ./containers/minio/
    - docker push $CI_REGISTRY_IMAGE/minio:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE/minio:latest

develop:
  stage: deploy
  only:
    - develop
  environment:
    name: staging
  tags:
    - shell
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  dependencies:
    - build
  script:
    - docker-compose pull
    - docker-compose up -d
